name: Build PWA to iOS Wrapper
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create Output Folder
        run: |
          mkdir -p ios-output
          find . -maxdepth 1 ! -name 'ios-output' ! -name '.' -exec cp -r {} ios-output/ \;
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Santana-XIT-iOS
          path: ios-output/
